services:
 facefusion-cpu:
  build:
   context: .
   dockerfile: Dockerfile.cpu
  command: [ 'python', 'facefusion.py', 'run' ]
  volumes:
  - .assets:/facefusion/.assets
  - .caches:/facefusion/.caches
  - .jobs:/facefusion/.jobs
  ports:
  - 7865:7860
