services:
  cuda:
    build:
      context: .
      dockerfile: Dockerfile.cuda
    command: ["python", "facefusion.py", "run", "--execution-providers", "cuda"]
    volumes:
      - .assets:/facefusion/.assets
      - .caches:/facefusion/.caches
      - .jobs:/facefusion/.jobs
      - .outputs:/tmp
    ports:
      - 7870:7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, video]
