services:
  cuda:
    build:
      context: .
      dockerfile: Dockerfile.cuda
    command:
      - python
      - main.py
      - --gpu-only
      - --listen
      - 0.0.0.0
      - --output-directory
      - /comfyui/output
      - --temp-directory
      - /comfyui/tmp
      - --input-directory
      - /comfyui/input
    volumes:
      - .models:/comfyui/models
      - .output:/comfyui/output
      - .input:/comfyui/input
      - .tmp:/comfyui/tmp
    ports:
      - 8188:8188
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, video]
