services:
  ollama-cpu:
    image: ollama/ollama
    volumes:
      - .ollama:/root/.ollama
    ports:
      - 11434:11434
    environment:
      - OLLAMA_DEBUG=0
      - GIN_MODE=release
  openwebui-cpu:
    image: ghcr.io/open-webui/open-webui:main
    volumes:
      - .openwebui:/app/backend/data
    ports:
      - 8080:8080
    environment:
      - WEBUI_AUTH=False
      - OLLAMA_BASE_URL=http://ollama-cpu:11434
